name: Docker Compose Workflow

on:
  push:
    branches:
      - master  # 触发工作流的分支，可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码到工作区

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置Docker Buildx

      - name: Run docker-compose up --build
        run: |
          docker-compose up --build -d  # 后台运行
