name: Docker Compose Workflow

on:
  push:
    branches:
      - main  # 触发工作流的分支，可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码到工作区

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub用户名，需要在仓库Secrets中设置
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub密码，需要在仓库Secrets中设置

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .  # Docker上下文路径
          file: ./Dockerfile  # Dockerfile路径
          push: true
          tags: user/app:latest  # 镜像标签，需要根据实际情况修改

      - name: Run docker-compose up --build
        run: |
          docker-compose up --build -d  # 后台运行
